"""
report.py — the Production Readiness Report (an exportable artifact).

Deterministic: it assembles everything OnePort Studio already knows about a repo
— the mind-map, the latest gate results, the verdict, the history and token use —
into one self-contained HTML document a developer can share with their lead for
sign-off. No AI, no rate limits: the same inputs always produce the same report.

Honest by construction: it prints exactly what the gates found (including skips
and errors) and states plainly that it is control evidence, not a certification.
"""
from __future__ import annotations

import html
from datetime import datetime, timezone


def _esc(s) -> str:
    return html.escape(str(s if s is not None else ""))


def _md_lite(text: str) -> str:
    """Tiny, safe Markdown → HTML for the generated README (headings/lists/code)."""
    out, in_list = [], False
    for raw in (text or "").splitlines():
        line = _esc(raw.rstrip())
        line = line.replace("`", "`")
        # inline code + bold (operate on escaped text)
        import re
        line = re.sub(r"`([^`]+)`", r"<code>\1</code>", line)
        line = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", line)
        s = line.strip()
        if s.startswith("### "):
            if in_list: out.append("</ul>"); in_list = False
            out.append(f"<h4>{s[4:]}</h4>")
        elif s.startswith("## "):
            if in_list: out.append("</ul>"); in_list = False
            out.append(f"<h3>{s[3:]}</h3>")
        elif s.startswith("# "):
            if in_list: out.append("</ul>"); in_list = False
            out.append(f"<h3>{s[2:]}</h3>")
        elif s.startswith(("- ", "* ")):
            if not in_list: out.append("<ul>"); in_list = True
            out.append(f"<li>{s[2:]}</li>")
        elif not s:
            if in_list: out.append("</ul>"); in_list = False
        else:
            if in_list: out.append("</ul>"); in_list = False
            out.append(f"<p>{s}</p>")
    if in_list:
        out.append("</ul>")
    return "\n".join(out)


def md_page(title: str, markdown: str, subtitle: str = "") -> str:
    """Render a Markdown document (e.g. a fix bundle) as a styled, printable
    artifact — same visual shell as the readiness report."""
    body = _md_lite(markdown) or '<p class="muted">(empty)</p>'
    from datetime import datetime, timezone
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{_esc(title)}</title>
<style>
  :root{{--ink:#1a1a1a;--soft:#5a5a5a;--faint:#8a8a8a;--line:#e4e4e4;--bg:#fafafa;--card:#fff}}
  *{{box-sizing:border-box}} body{{margin:0;background:var(--bg);color:var(--ink);
    font-family:-apple-system,"Segoe UI",system-ui,sans-serif;line-height:1.6;font-size:14px}}
  .wrap{{max-width:820px;margin:0 auto;padding:40px 28px 64px}}
  header{{border-bottom:2px solid var(--ink);padding-bottom:14px;margin-bottom:22px}}
  h1{{font-size:1.4rem;margin:0;letter-spacing:-.02em}} .sub{{color:var(--soft);font-size:.82rem;margin-top:4px}}
  .doc h2,.doc h3{{font-size:1.05rem;margin:22px 0 6px;padding-top:14px;border-top:1px solid var(--line)}}
  .doc h2:first-child,.doc h3:first-child{{border-top:none;padding-top:0}}
  .doc h4{{font-size:.92rem;margin:14px 0 4px;color:var(--soft)}}
  .doc p{{margin:8px 0}} .doc ul{{padding-left:20px}} .doc li{{margin:4px 0}}
  .doc code{{font-family:ui-monospace,"SF Mono",Menlo,monospace;font-size:.85em;background:#f1f1f1;padding:1px 5px;border-radius:4px}}
  .doc strong{{color:var(--ink)}}
  footer{{margin-top:36px;padding-top:14px;border-top:1px solid var(--line);color:var(--faint);font-size:.75rem}}
  @media print{{body{{background:#fff}}}}
</style></head><body><div class="wrap">
  <header><h1>{_esc(title)}</h1><div class="sub">{_esc(subtitle or "OnePort — AI remediation bundle")} · {_esc(now)}</div></header>
  <div class="doc">{body}</div>
  <footer>Generated by OnePort. AI-suggested fixes — review before applying; the model can be wrong.</footer>
</div></body></html>"""


_STATUS_LABEL = {"pass": "PASS", "block": "BLOCK", "error": "ERROR", "skip": "SKIP"}


def generate(project: dict, manifest: dict) -> str:
    name = project.get("name", "repo")
    path = project.get("path", "")
    hist = project.get("history", []) or []
    latest = hist[0] if hist else None
    verdict = (project.get("last_verdict") or "NOT SCANNED").upper()
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    files = manifest.get("files", {}) or {}
    roles: dict[str, int] = {}
    for info in files.values():
        r = info.get("role", "other")
        roles[r] = roles.get(r, 0) + 1
    roles_sorted = sorted(roles.items(), key=lambda kv: -kv[1])

    s = (latest or {}).get("summary", {}) if latest else {}
    gates = (latest or {}).get("gates", []) if latest else []
    blocking = [g for g in gates if g.get("status") == "block"]
    errored = [g for g in gates if g.get("status") == "error"]

    vcolor = {"READY": "#1a7f37", "BLOCKED": "#b91c1c",
              "INCONCLUSIVE": "#9a6700"}.get(verdict, "#555")

    def stat(label, value, sub=""):
        return (f'<div class="stat"><div class="sv">{_esc(value)}</div>'
                f'<div class="sl">{_esc(label)}</div>'
                f'{f"<div class=\"ss\">{_esc(sub)}</div>" if sub else ""}</div>')

    gate_rows = "".join(
        f'<tr class="{_esc(g.get("status"))}"><td class="gname">{_esc(g.get("title"))}</td>'
        f'<td><span class="badge {_esc(g.get("status"))}">{_STATUS_LABEL.get(g.get("status"), _esc(g.get("status")))}</span></td>'
        f'<td class="gsum">{_esc(g.get("summary"))}</td></tr>'
        for g in gates) or '<tr><td colspan="3" class="muted">No scan yet — run Test for Production.</td></tr>'

    block_html = ""
    if blocking or errored:
        items = "".join(f"<li><strong>{_esc(g.get('title'))}</strong> — {_esc(g.get('summary'))}</li>"
                        for g in (blocking + errored))
        block_html = (f'<div class="callout"><h3>Must fix before production '
                      f'({len(blocking)} blocking, {len(errored)} errored)</h3><ul>{items}</ul></div>')

    roles_html = "".join(
        f'<div class="role"><span class="rn">{_esc(r)}</span><span class="rc">{n}</span></div>'
        for r, n in roles_sorted) or '<div class="muted">Mind-map not built yet.</div>'

    hist_html = "".join(
        f'<div class="hrow"><span class="hv {_esc(h.get("verdict"))}">{_esc(h.get("verdict"))}</span>'
        f'<span class="ht">{_esc(h.get("trigger"))}{" · prod" if h.get("mode") == "production" else ""}</span>'
        f'<span class="hd">{_esc((h.get("ts") or "")[:19].replace("T", " "))}</span>'
        f'<span class="hs">{(h.get("summary") or {}).get("pass", 0)}✓ '
        f'{(h.get("summary") or {}).get("block", 0)}✕ {(h.get("summary") or {}).get("error", 0)}!</span></div>'
        for h in hist[:12]) or '<div class="muted">No runs recorded.</div>'

    readme_html = _md_lite(manifest.get("readme", "")) or '<p class="muted">No overview generated yet — build the mind-map.</p>'

    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>OnePort Report — {_esc(name)}</title>
<style>
  :root{{--ink:#1a1a1a;--soft:#5a5a5a;--faint:#8a8a8a;--line:#e4e4e4;--bg:#fafafa;--card:#fff}}
  *{{box-sizing:border-box}} body{{margin:0;background:var(--bg);color:var(--ink);
    font-family:-apple-system,"Segoe UI",system-ui,sans-serif;line-height:1.55;font-size:14px}}
  .wrap{{max-width:820px;margin:0 auto;padding:40px 28px 64px}}
  .mono{{font-family:ui-monospace,"SF Mono",Menlo,monospace}}
  header{{display:flex;align-items:flex-start;justify-content:space-between;gap:20px;
    border-bottom:2px solid var(--ink);padding-bottom:18px;margin-bottom:26px}}
  h1{{font-size:1.5rem;margin:0 0 4px;letter-spacing:-.02em}}
  .sub{{color:var(--soft);font-size:.85rem}}
  .path{{font-family:ui-monospace,Menlo,monospace;font-size:.78rem;color:var(--faint);margin-top:4px;word-break:break-all}}
  .verdict{{text-align:right;flex:none}}
  .vbadge{{display:inline-block;font-weight:700;font-size:1rem;letter-spacing:.03em;
    color:#fff;background:{vcolor};padding:8px 16px;border-radius:8px}}
  .vwhen{{color:var(--faint);font-size:.72rem;margin-top:6px}}
  h2{{font-size:.78rem;letter-spacing:.1em;text-transform:uppercase;color:var(--faint);
    font-family:ui-monospace,Menlo,monospace;margin:32px 0 12px;font-weight:600}}
  .stats{{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}}
  .stat{{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:14px}}
  .sv{{font-size:1.5rem;font-weight:700;letter-spacing:-.02em}}
  .sl{{font-size:.72rem;color:var(--faint);text-transform:uppercase;letter-spacing:.04em;margin-top:2px}}
  .ss{{font-size:.72rem;color:var(--soft);margin-top:2px}}
  table{{width:100%;border-collapse:collapse;background:var(--card);border:1px solid var(--line);border-radius:10px;overflow:hidden}}
  td,th{{text-align:left;padding:11px 14px;border-bottom:1px solid var(--line);font-size:.86rem;vertical-align:top}}
  tr:last-child td{{border-bottom:none}}
  .gname{{font-weight:600;width:200px}} .gsum{{color:var(--soft)}}
  .badge{{font-family:ui-monospace,Menlo,monospace;font-size:.7rem;font-weight:700;padding:2px 8px;border-radius:5px;white-space:nowrap}}
  .badge.pass{{background:#dcfce7;color:#166534}} .badge.block{{background:#fee2e2;color:#991b1b}}
  .badge.error{{background:#fef3c7;color:#92400e}} .badge.skip{{background:#f1f1f1;color:#6a6a6a}}
  .callout{{background:#fef2f2;border:1px solid #fecaca;border-radius:10px;padding:14px 18px;margin:16px 0}}
  .callout h3{{margin:0 0 8px;font-size:.95rem;color:#991b1b}}
  .callout ul{{margin:0;padding-left:18px}} .callout li{{margin:4px 0;font-size:.86rem}}
  .roles{{display:flex;flex-wrap:wrap;gap:8px}}
  .role{{display:flex;align-items:center;gap:7px;background:var(--card);border:1px solid var(--line);border-radius:999px;padding:5px 12px;font-size:.8rem}}
  .rc{{font-family:ui-monospace,Menlo,monospace;color:var(--faint);font-weight:600}}
  .overview{{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:6px 20px}}
  .overview h3{{font-size:1rem;margin:16px 0 6px}} .overview h4{{font-size:.9rem;margin:12px 0 4px}}
  .overview code{{font-family:ui-monospace,Menlo,monospace;font-size:.85em;background:#f3f3f3;padding:1px 5px;border-radius:4px}}
  .overview ul{{padding-left:20px}} .overview p{{margin:8px 0;color:var(--soft)}}
  .hrow{{display:flex;align-items:center;gap:12px;padding:8px 0;border-bottom:1px solid var(--line);font-size:.82rem}}
  .hrow:last-child{{border-bottom:none}}
  .hv{{font-family:ui-monospace,Menlo,monospace;font-weight:700;font-size:.72rem;color:#fff;padding:2px 8px;border-radius:5px;background:#888}}
  .hv.READY{{background:#1a7f37}} .hv.BLOCKED{{background:#b91c1c}} .hv.INCONCLUSIVE{{background:#9a6700}}
  .ht{{color:var(--soft);font-family:ui-monospace,Menlo,monospace;font-size:.72rem}}
  .hd{{color:var(--faint);font-family:ui-monospace,Menlo,monospace;font-size:.74rem;margin-left:auto}}
  .hs{{font-family:ui-monospace,Menlo,monospace;font-size:.74rem;color:var(--soft)}}
  .muted{{color:var(--faint)}}
  footer{{margin-top:40px;padding-top:16px;border-top:1px solid var(--line);color:var(--faint);font-size:.75rem}}
  @media print{{body{{background:#fff}} .stat,table,.overview,.role{{break-inside:avoid}}}}
</style></head><body><div class="wrap">
  <header>
    <div><h1>{_esc(name)}</h1>
      <div class="sub">Production Readiness Report</div>
      <div class="path">{_esc(path)}</div></div>
    <div class="verdict"><span class="vbadge">{_esc(verdict)}</span>
      <div class="vwhen">{_esc(now)}</div></div>
  </header>

  <h2>At a glance</h2>
  <div class="stats">
    {stat("Passed", s.get("pass", 0), "gates")}
    {stat("Blocking", s.get("block", 0), "must fix")}
    {stat("Errored", s.get("error", 0), "inconclusive")}
    {stat("Files mapped", len(files), f"{project.get('tokens_used', 0):,} tokens")}
  </div>

  {block_html}

  <h2>Gate results</h2>
  <table><tr><th>Gate</th><th>Status</th><th>Detail</th></tr>{gate_rows}</table>

  <h2>Repository map · {len(files)} files</h2>
  <div class="roles">{roles_html}</div>

  <h2>Overview</h2>
  <div class="overview">{readme_html}</div>

  <h2>Recent history</h2>
  <div>{hist_html}</div>

  <footer>Generated by OnePort — deterministically from this project's ship data.
  This is control evidence for your team's review, not a security certification.
  Skipped or errored gates are shown explicitly; a clean report never hides them.</footer>
</div></body></html>"""
